# permissions for end users to view spires.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spire-viewer-role
rules:
- apiGroups:
  - spire.spiffe.io
  resources:
  - spires
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spire.spiffe.io
  resources:
  - spires/status
  verbs:
  - get
