# permissions for end users to edit spires.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spire-editor-role
rules:
- apiGroups:
  - spire.spiffe.io
  resources:
  - spires
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spire.spiffe.io
  resources:
  - spires/status
  verbs:
  - get
