apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: {{ .Release.Namespace}}
spec:
  type: NodePort
  ports:
    - name: grpc
      port: {{ .Values.config.server.port }}
      targetPort: {{ .Values.config.server.port }}
      protocol: TCP
  selector:
    app: spire-server
