apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-server
  namespace: {{ .Release.Namespace}}
data:
  server.conf: |
    server {
      bind_address = "{{ .Values.config.server.bindAddress }}"
      bind_port = "{{ .Values.config.server.port }}"
      registration_uds_path = "/tmp/spire-registration.sock"
      trust_domain = "{{ .Values.config.trustDomain }}"
      data_dir = "/run/spire/data"
      log_level = "DEBUG"
      #AWS requires the use of RSA.  EC cryptography is not supported
      ca_key_type = "rsa-2048"

      default_svid_ttl = "1h"
      ca_subject = {
        country = ["US"],
        organization = ["SPIFFE"],
        common_name = "",
      }
    }

    plugins {
      DataStore "sql" {
        plugin_data {
          database_type = "sqlite3"
          connection_string = "/run/spire/data/datastore.sqlite3"
        }
      }

      NodeAttestor "k8s_sat" {
        plugin_data {
          clusters = {
            # NOTE: Change this to your cluster name
            "{{.Values.config.server.plugins.noteAttestor.clusterName}}" = {
              use_token_review_api_validation = true
              service_account_whitelist = ["{{.Release.Namespace}}:spire-agent"]
            }
          }
        }
      }

      NodeResolver "noop" {
        plugin_data {}
      }

      KeyManager "disk" {
        plugin_data {
          keys_path = "/run/spire/data/keys.json"
        }
      }

      Notifier "k8sbundle" {
        plugin_data {
        }
      }
    }
