config:
  trustDomain: example.org
  server:
    image:
      repository: gcr.io/spiffe-io/spire-server
      tag: 0.10.0
    replicas: 1
    port: 8081
    bindAddress: 0.0.0.0
    plugins:
      noteAttestor:
        clusterName: demo-cluster
  
  agent:
    clusterName: demo-cluster
    image:
      repository: gcr.io/spiffe-io/spire-agent
      tag: 0.10.0